[package]
name = "warnings"
version = "0.2.0"
edition = "2021"

[dependencies]
pin-project = "1"
warnings-macro = { path = "./warnings-macro" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
warnings = { path = "." }

[workspace]
members = ["./warnings-macro"]